replicaCount: 2

image:
  repository: estahn/httpbingo
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  path: /get
  pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.http-method-check: |  # Conditions for GET only
      [{"type":"forward","forwardConfig":{"targetGroupArn":"{{ .Values.ingress.targetGroupArn }}"}}]
    alb.ingress.kubernetes.io/healthcheck-path: /status/200
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/load-balancer-name: httpbin-public-alb